swagger: '2.0'
info:
  title: GitHub Auth Example API
  version: 1.0.0
host: localhost:3000
schemes:
  - http
paths:
  /auth/github:
    get:
      tags:
        - Authentication
      summary: Redirects to GitHub authentication page
      responses:
        302:
          description: Redirect to GitHub for authentication
  /auth/github/callback:
    get:
      tags:
        - Authentication
      summary: GitHub callback URL
      responses:
        200:
          description: Authentication successful
        401:
          description: Authentication failed
